version: "3.2"
services:
  backend:
    build: ./Kapo_Back
    volumes:
      - ./Kapo_Back:/app/backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./Kapo_Front/kapo
    volumes:
      - ./Kapo_Front/kapo:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start