# Generated by Django 3.0.1 on 2020-01-09 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200109_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='corporate_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(100000000000)], verbose_name='corporate number'),
        ),
    ]
