# Generated by Django 3.0.1 on 2020-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200210_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='photo'),
        ),
    ]
