# Generated by Django 3.0.1 on 2020-02-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=2, verbose_name='balance'),
        ),
    ]
