# Generated by Django 3.0.1 on 2020-02-14 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=2, verbose_name='balance'),
        ),
    ]
