# Generated by Django 3.0.1 on 2019-12-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='products/<django.db.models.fields.AutoField>/', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('main_category', models.CharField(choices=[('1', 'Digital'), ('2', 'Health-Care'), ('3', 'Tools, office supplies and car'), ('4', 'Fashion'), ('5', 'Home appliance'), ('6', 'Book, stationary and art'), ('7', 'Toys and baby'), ('8', 'Sport and traveling'), ('9', 'Food and drink')], max_length=100, verbose_name='category')),
                ('price', models.IntegerField(verbose_name='price')),
                ('second_hand', models.BooleanField(verbose_name='second hand')),
                ('available', models.BooleanField(verbose_name='available')),
                ('visited_num', models.IntegerField(verbose_name='visit count')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['created_date'],
            },
        ),
    ]
