# Generated by Django 3.0.1 on 2019-12-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/98900269651449678041/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/55255340814612051517/'),
        ),
    ]
