# Generated by Django 3.0.1 on 2019-12-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0002_auto_20191223_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False, verbose_name='available'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/<django.db.models.fields.AutoField>/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('0', 'Default'), ('1', 'Digital'), ('2', 'Health-Care'), ('3', 'Tools, office supplies and car'), ('4', 'Fashion'), ('5', 'Home appliance'), ('6', 'Book, stationary and art'), ('7', 'Toys and baby'), ('8', 'Sport and traveling'), ('9', 'Food and drink')], default=0, max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_hand',
            field=models.BooleanField(default=False, verbose_name='second hand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visited_num',
            field=models.IntegerField(default=0, verbose_name='visit count'),
        ),
    ]
