# Generated by Django 3.0.1 on 2019-12-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0003_auto_20191223_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='visited_num',
            new_name='visit_count',
        ),
    ]
