# Generated by Django 3.0.1 on 2019-12-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0005_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/36413463663196072722/', verbose_name='image'),
        ),
    ]
