# Generated by Django 3.0.1 on 2019-12-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0011_auto_20191227_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/77385159770588859764/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/71184983636924906935/'),
        ),
    ]
