# Generated by Django 3.0.1 on 2020-02-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
    ]
