# Generated by Django 3.0.1 on 2020-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, 'Awaiting'), (2, 'Completed'), (3, 'Failed')], default=1, verbose_name='state'),
        ),
    ]
