# Generated by Django 3.0.1 on 2020-02-02 19:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredSearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)], verbose_name='search count')),
                ('remaining_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='remaining count')),
                ('valid', models.BooleanField(default=True, verbose_name='valid')),
                ('search_phrases', models.CharField(max_length=20, verbose_name='search phrases')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_searches', to='kapo.Product')),
            ],
        ),
    ]
