# Generated by Django 3.0.1 on 2020-02-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat1',
            field=models.CharField(choices=[('1', 'electronics'), ('2', 'personal'), ('3', 'businesses'), ('4', 'car'), ('5', 'home-appliance'), ('6', 'leisure-and-hobbies')], max_length=100, verbose_name='cat1'),
        ),
    ]
