# Generated by Django 3.0.1 on 2020-02-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kapo', '0002_auto_20200214_1016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('content_type', 'object_id')},
        ),
    ]
