# Generated by Django 3.0.1 on 2020-01-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0002_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('0', 'Default'), ('1', 'Digital'), ('2', 'Health-Care'), ('3', 'Tools, Office Supplies, Car'), ('4', 'Fashion'), ('5', 'Home Appliance'), ('6', 'Books, Stationary, Arts'), ('7', 'Toys, Baby'), ('8', 'Sport'), ('9', 'Food, Drink')], default='0', max_length=100, verbose_name='category'),
        ),
    ]
