# Generated by Django 3.0.1 on 2020-02-09 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0002_sponsoredsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredsearch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='registration date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsoredsearch',
            name='state',
            field=models.IntegerField(choices=[(1, 'Awaiting'), (2, 'Completed')], default=1, verbose_name='state'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valid', models.BooleanField(default=True, verbose_name='valid')),
                ('state', models.IntegerField(choices=[(1, 'Awaiting'), (2, 'Completed')], default=1, verbose_name='state')),
                ('place', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=1, verbose_name='place')),
                ('days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='days')),
                ('remaining_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='remaining_days')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='kapo.Product')),
            ],
        ),
    ]
