# Generated by Django 3.0.3 on 2020-02-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0003_balanceincrease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
