# Generated by Django 3.0.1 on 2020-02-14 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kapo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('kapo', '0005_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'Sponsor'), (2, 'Banner'), (3, 'Campaign'), (4, 'Order'), (5, 'Increase Balance'), (6, 'Liquidate')], verbose_name='type'),
        ),
        migrations.CreateModel(
            name='Liquidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidate', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(kapo.models.TransactionMixin, models.Model),
        ),
    ]
