# Generated by Django 3.0.2 on 2020-02-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0005_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slogan',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='slogan'),
        ),
    ]
