# Generated by Django 3.0.1 on 2020-02-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0006_banner_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(default='', verbose_name='image'),
        ),
    ]
