# Generated by Django 3.0.1 on 2020-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapo', '0007_auto_20200211_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_hours',
            field=models.IntegerField(choices=[(1, 'Nine Twelve'), (2, 'Twelve Fifteen'), (3, 'Fifteen Eighteen')], default=1, verbose_name='delivery_hours'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_weekday',
            field=models.IntegerField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')], default=1, verbose_name='delivery_weekday'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, default='', null=True, verbose_name='image'),
        ),
    ]
