# Generated by Django 3.0.1 on 2020-02-13 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('kapo', '0010_product_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('total_amount', models.IntegerField(verbose_name='total_amount')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
